apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
helmCharts:
  - name: loki-stack
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: loki-stack
    includeCRDs: true
    skipTests: true
    valuesInline:
      grafana:
        enabled: false