apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.30.1
    releaseName: loki
    namespace: loki-stack
    includeCRDs: true
    skipTests: true
    valuesFile: values.yaml
        