[package]
name = "rust-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
reqwest = "0.12.19"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "fs"] }
