apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: default
  labels:
    app: rust-api
spec:
  
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      volumes:
      - name: pic
        persistentVolumeClaim:
          claimName: pic-pvc
      containers:
      - name: rust-api
        image: rust-api
        volumeMounts:
          - name: pic
            mountPath: /usr/src/app/files