apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: project
  labels:
    app: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      volumes:
      - name: pic
        persistentVolumeClaim:
          claimName: pic-pvc
      containers:
      - name: rust-api
        image: rust-api
        envFrom:
          - configMapRef:
              name: backend-config
          - configMapRef:
              name: db-config
          - secretRef:
              name: db-secret
        volumeMounts:
          - name: pic
            mountPath: /usr/src/app/files
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"