apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: default
  labels:
    app: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: dev-registry.localhost:5000/rust-api