apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: pic-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
