apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: project
  labels:
    app: nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: nginx-frontend