apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: monitoring
    includeCRDs: true
    skipTests: true
    namespace: prometheus
    valuesInline:
      grafana:
        additionalDataSources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.loki-stack.svc.cluster.local
            jsonData:
              tlsSkipVerify: true
              httpHeaderName1: 'X-Scope-OrgID'
            secureJsonData:
              httpHeaderValue1: 'empty'
              